Allow guzzlehttp/psr7=^2.0, while retaining BC
http-interop/http-factory-guzzle pull request #13
Opened 2021-07-06 07:59 UTC by nederdirk

Hi, recently `guzzlehttp/psr7` received a major version upgrade. Not much has changed, but I updated this lib (with backwards compatibility in mind) to also be able to use `guzzlehttp/psr7=^2.0`

2021-07-11 11:54 UTC, proggeler commented
@nederdirk I stumbled on this problem too. Thanks for your fix. I hope it gets merged soon.

2021-07-17 17:01 UTC, shadowhand reviewed
Rather than taking this approach, I think the appropriate thing to do would be to switch to `guzzlehttp/psr7 ^2.0` and then release a new major version of this package. I don't see a lot of value in allowing both versions.

2021-07-17 17:01 UTC, shadowhand requested changes
See previous comment.

2021-07-19 07:37 UTC, nederdirk commented
> Rather than taking this approach, I think the appropriate thing to do would be to switch to `guzzlehttp/psr7 ^2.0` and then release a new major version of this package. I don't see a lot of value in allowing both versions.

I don't agree completely with that statement. `http-interop/http-factory-guzzle` is often used as a dependency of other libraries[^1], and having only a major version upgrade available would force those libraries to explicit version updates.
As an example, the codebase of my employer depends on `sentry/sdk=^3` which in turn depends on `http-interop/http-factory-guzzle=^1`. Having `http-interop/http-factory-guzzle` require a major version upgrade, would still prevent us from taking the future-compatible path to `guzzlehttp/psr7=^2.0`.

[^1]: https://github.com/http-interop/http-factory-guzzle/network/dependents?dependent_type=PACKAGE

Would it be an option to you to release a minor version update, allowing for `guzzlehttp/psr7=^1 || ^2`, and directly afterward releasing a major version update requiring `guzzlehttp/psr7=^2`, so downstream libraries have a bit of time to make the transition?

2021-07-19 14:41 UTC, vanthao03596 commented
Waiting for merge !

2021-07-19 15:00 UTC, shadowhand commented
@nederdirk that is a reasonable compromise.

2021-07-19 15:00 UTC, shadowhand approved these changes

2021-07-19 15:00 UTC, merged

2021-07-19 15:18 UTC, shadowhand commented
Released in version 1.1.0.

2021-07-19 21:54 UTC, GrahamCampbell commented
`guzzlehttp/psr7: ^1.7 || ^2.0` would allow you to use the new static class methods and not have those function exists hacks.

2021-07-20 12:13 UTC, shadowhand commented
@GrahamCampbell I had no idea, thanks for letting me know. I'll make that change and release 1.1.1.

2021-07-23 14:52 UTC, shadowhand commented
Oh crap, I just realized the bug. The function exists check isn't using the full namespace, so it is not properly falling back to legacy Guzzle functions.

I will make a patch release ASAP, and fix tests.